### ISSUE TITLE
Give Individuals Admin Privilege, Do Away Single Admin Account

### ISSUE THREAD

**Issue by grinnelldennis** [CSC322-Grinnell/mayflower-directory#182]
As an admin,
So that I don't have to login to the single, shared admin acct.
I want to have admin privilege associated with my personal account.

**Comment by lequytra** [comment]
I don't see what we can do for this issue. Our client can create admin accounts if they want to.

**Comment by JohnLennon1997** [comment]
Go into Heroku and run user-edit! on the rails console
